version: '3.4'

services:
  roomsense-backend:
    image: ${DOCKER_REGISTRY-}roomsensebackend
    build:
      context: RoomSense-Backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    depends_on:
      - roomsense-database
    environment:
      - ConnectionStringRoomSenseDB=Server=roomsense-database;Port=5432;Database=roomsense;User Id=roomsense-service;Password=iot;
      - MQTT_BROKER_URL=c93e99eaf93b4f81aa4db3ba6fee2780.s1.eu.hivemq.cloud
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USERNAME=service
      - MQTT_BROKER_PASSWORD=Service1
      - TEMPERATURE_THRESHOLD=30
      - CO2_THRESHOLD=1000
      - ALARM_PROCESSING_SERVICE_DELAY_MINUTES=1
      - RECOMMENDATION_PROCESSING_SERVICE_DELAY_MINUTES=1 
    networks:
      - roomsense-network

  roomsense-database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=roomsense-service
      - POSTGRES_PASSWORD=iot
      - POSTGRES_DB=roomsense
    ports:
      - "5432:5432"
    networks:
      - roomsense-network
 
  sensor-simulator-1:
    image: ${DOCKER_REGISTRY-}sensorsimulator
    build:
      context: SensorSimulator
      dockerfile: Dockerfile
    depends_on:
      - roomsense-backend
    ports:
      - "8080:80"
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    environment:
      - MQTT_BROKER_URL=c93e99eaf93b4f81aa4db3ba6fee2780.s1.eu.hivemq.cloud
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USERNAME=sensor-simulator-1
      - MQTT_BROKER_PASSWORD=SensorSim123
      - MQTT_TOPIC=room/simulator1
    networks:
      - roomsense-network 
- 
  sensor-simulator-2:
    image: ${DOCKER_REGISTRY-}sensorsimulator
    build:
      context: SensorSimulator
      dockerfile: Dockerfile
    depends_on:
      - roomsense-backend
    ports:
      - "8080:80"
      - "1883:1883"
      - "8883:8883"
      - "8884:8884"
    environment:
      - MQTT_BROKER_URL=c93e99eaf93b4f81aa4db3ba6fee2780.s1.eu.hivemq.cloud
      - MQTT_BROKER_USERNAME=sensor-simulator-2
      - MQTT_BROKER_PASSWORD=SensorSim123
      - MQTT_TOPIC=room/simulator2
      - MQTT_BROKER_PORT=8883
    networks:
      - roomsense-network 

networks:
  roomsense-network:
    driver: bridge