version: '3.4'

services:

  sensor-simulator-1:
    image: ${DOCKER_REGISTRY-}sensorsimulator
    build:
      context: SensorSimulator
      dockerfile: Dockerfile
    ports:
      - "8082:80"    # Changed from 8080 to 8082
      - "1885:1883"  # Changed from 1883 to 1885
      - "8887:8883"  # Changed from 8883 to 8887
      - "8888:8884"  # Changed from 8884 to 8888
    environment:
      - MQTT_BROKER_URL=c93e99eaf93b4f81aa4db3ba6fee2780.s1.eu.hivemq.cloud
      - MQTT_BROKER_PORT=8883
      - MQTT_BROKER_USERNAME=sensor-simulator-1
      - MQTT_BROKER_PASSWORD=SensorSim123
      - MQTT_TOPIC=room/simulator1
    networks:
      - roomsense-network 

  sensor-simulator-2:
    image: ${DOCKER_REGISTRY-}sensorsimulator
    build:
      context: SensorSimulator
      dockerfile: Dockerfile
    ports:
      - "8083:80"    # Changed from 8080 to 8083
      - "1886:1883"  # Changed from 1883 to 1886
      - "8889:8883"  # Changed from 8883 to 8889
      - "8890:8884"  # Changed from 8884 to 8890
    environment:
      - MQTT_BROKER_URL=c93e99eaf93b4f81aa4db3ba6fee2780.s1.eu.hivemq.cloud
      - MQTT_BROKER_USERNAME=sensor-simulator-2
      - MQTT_BROKER_PASSWORD=SensorSim123
      - MQTT_TOPIC=room/simulator2
      - MQTT_BROKER_PORT=8883
    networks:
      - roomsense-network 

networks:
  roomsense-network:
    driver: bridge